import Link from "next/link";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { BookingBar } from "@/components/BookingBar";
import { hotel } from "@/data/hotel";
import { rooms } from "@/data/rooms";
import { amenities } from "@/data/amenities";
import { location } from "@/data/location";
import { HotelMap } from "@/components/HotelMap";
import { GuestExperiences } from "@/components/GuestExperiences";
export default function Home() { return <><div className="hero"><SiteHeader/><div className="heroCopy"><p className="eyebrow">Marrakech · Morocco</p><h1>ibis Marrakech<br/><em>Palmeraie</em></h1><p>A calm, contemporary stay near the Palm Grove—made for seeing Marrakech at your own pace.</p><div className="heroActions"><a className="button" href="#book">Book your stay</a><a className="textLink" href="#discover">Discover the hotel <ArrowDownRight/></a></div></div><p className="heroCaption">A modern hotel in the colours of the Ochre City</p></div><BookingBar/><section id="discover" className="intro section"><div><p className="eyebrow">The hotel</p><h2>Quietly placed.<br/><em>Well connected.</em></h2></div><div><p>Set close to Marrakech’s Palm Grove, ibis Marrakech Palmeraie brings together an easygoing atmosphere and practical comforts for business or leisure stays.</p><p>Its 147 air-conditioned rooms, outdoor pool, restaurant and bar create a considered base beyond the city’s rush.</p><Link className="textLink" href="/hotel">Our story <ArrowUpRight/></Link></div></section><section className="rooms section"><div className="sectionTitle"><div><p className="eyebrow">Stay your way</p><h2>Room to <em>unwind.</em></h2></div><Link className="textLink" href="/rooms">View all rooms <ArrowUpRight/></Link></div><div className="roomGrid">{rooms.map((room, index) => <article className={`roomCard roomCard--${index + 1}`} key={room.slug}><div className="roomVisual"><span>{String(index + 1).padStart(2,"0")}</span></div><div><p className="eyebrow">{room.capacity} · {room.bed}</p><h3>{room.name}</h3><p>{room.description}</p><Link className="textLink" href={`/rooms/${room.slug}`}>Explore room <ArrowUpRight/></Link></div></article>)}</div></section><section className="experience"><div className="experienceVisual"><p>Poolside<br/><em>light.</em></p></div><div className="experienceCopy"><p className="eyebrow">At your leisure</p><h2>Sun, shade, and a slower <em>moment.</em></h2><p>Step out onto the terrace, take a dip in the outdoor pool, or linger over a meal at the hotel’s international restaurant and bar.</p><p className="muted">Pool and food-service opening times are available from reception.</p></div></section><section className="amenities section"><p className="eyebrow">Made easy</p><h2>Everything for a comfortable <em>stay.</em></h2><div className="amenityGrid">{amenities.map(({name, Icon}) => <div key={name}><Icon size={22}/><span>{name}</span></div>)}</div></section><GuestExperiences/><section className="location section"><div><p className="eyebrow">Find us</p><h2>At the edge of the <em>Palmeraie.</em></h2><p>{location.address}</p><a className="button button--dark" href={location.googleMapsUrl} target="_blank">Get directions <ArrowUpRight/></a></div><HotelMap/></section><section className="reserve"><p className="eyebrow">Your Marrakech stay</p><h2>Starts <em>here.</em></h2><a className="button" href="#book">Book your stay</a></section><SiteFooter/></>; }
