import { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FinalBookingCta } from "@/components/FinalBookingCta";
import { ImageSlot } from "@/components/ImageSlot";
import { PageHero } from "@/components/PageHero";
import { SiteFooter } from "@/components/SiteFooter";
import { hotel } from "@/data/hotel";
import { getRoomBySlug, rooms } from "@/data/rooms";
import { pageMetadata } from "@/lib/metadata";

export function generateStaticParams() { return rooms.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const room = getRoomBySlug(slug); return room ? pageMetadata(room.name, room.description, `/rooms/${room.slug}`) : { title: "Room not found" }; }); }

export default async function RoomPage({ params }: { params: Promise<{ slug: string }> }) { const room = getRoomBySlug((await params).slug); if (!room) notFound(); const related = rooms.filter(({ slug }) => slug !== room.slug).slice(0, 3); const distinction = room.view || (room.slug === "junior-suite-sofa" ? "Double bed and sofa" : "Standard room category"); return <><PageHero eyebrow={`${room.capacity} · ${room.bed}`} title={room.name}><a className="button roomHeroButton" href={hotel.bookingUrl} target="_blank" rel="noreferrer">Book your stay</a></PageHero><main className="roomDetail"><section className="section roomIntroDetail"><p className="lead">{room.description}</p><ImageSlot label={room.name} ratio="wide" /></section><section className="section roomInformation"><div><p className="eyebrow">The essentials</p><h2>Comfort, covered.</h2><ul><li>Private bathroom</li><li>Desk area</li><li>Television</li><li>Free Wi-Fi</li><li>Air conditioning</li></ul></div><div><p className="eyebrow">Good to know</p><h2>Details for your stay.</h2><dl><div><dt>Capacity</dt><dd>{room.capacity}</dd></div><div><dt>Bedding</dt><dd>{room.bed}</dd></div><div><dt>Category detail</dt><dd>{distinction}</dd></div></dl></div></section><section className="section roomFutureGallery"><div className="sectionTitle"><div><p className="eyebrow">A room, in more detail</p><h2>Ready for approved <em>photography.</em></h2></div><p className="collectionNote">Future images will be clearly captioned and supplied by the hotel.</p></div><div className="roomSlotGrid"><ImageSlot label={`${room.name} — sleeping area`} ratio="landscape" /><ImageSlot label={`${room.name} — work area`} ratio="portrait" /><ImageSlot label={`${room.name} — bathroom`} ratio="square" /></div></section><section className="section relatedRooms"><div className="sectionTitle"><div><p className="eyebrow">Continue exploring</p><h2>Explore other <em>rooms.</em></h2></div><Link className="textLink" href="/rooms">Back to rooms</Link></div><div>{related.map((item) => <Link key={item.slug} className="relatedRoom" href={`/rooms/${item.slug}`}><span>{item.capacity} · {item.bed}</span><strong>{item.name}</strong><small>Explore room ↗</small></Link>)}</div></section></main><FinalBookingCta eyebrow="Choose your Marrakech stay" title={<>Make room for <em>more.</em></>} /><SiteFooter /></>; }
